server {
    listen 80;
    server_name api.test;

    location /users {
        proxy_pass http://user-service:8000;
    }

    location /products {
        proxy_pass http://product-service:8000;
    }

    location /orders {
        proxy_pass http://order-service:8000;
    }
}